// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgjfiflfsrsyzwnafnaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnamZpZmxmc3JzeXp3bmFmbmFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDQwMDEsImV4cCI6MjA2NzIyMDAwMX0.Q8avL-09lYuZHQul-q2QN7WMSdR4WR7-eCAuXMniPZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});